# Generated by Django 4.2 on 2023-05-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['start_date']},
        ),
    ]
