# Generated by Django 4.2 on 2023-05-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_alter_flight_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['start_date']},
        ),
    ]
