# Generated by Django 4.2 on 2023-05-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0003_alter_event_options_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date']},
        ),
    ]
