# Generated by Django 4.2 on 2023-05-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0004_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='flights',
            field=models.ManyToManyField(blank=True, null=True, to='earnings.flight'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotels',
            field=models.ManyToManyField(blank=True, null=True, to='earnings.hotel'),
        ),
    ]
